services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: facility
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/facility
      AWS_REGION: eu-central-1
      S3_BUCKET: facility-feed-service
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "src/main.py"]

volumes:
  postgres_data:
