name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linting
        run: flake8 .

      - name: Run Tests
        run: pytest

      - name: Build Docker Image
        run: docker build -t my-service .

      - name: Log in to AWS ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY

      - name: Tag Docker Image
        run: |
          docker tag my-service:latest ${{ secrets.AWS_ECR_REGISTRY }}:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}:latest
